name: Go CI
description: GitHub Actions for building and testing Go projects

inputs:
  project-path:
    description: The path to the project
    type: string
    required: false
    default: ''
  go-version:
    description: The version of Go to use
    type: string
    required: false
    default: 'stable'
  golang-ci-lint-version:
    description: The version of golangci-lint to use
    type: string
    required: false
    default: 'latest'
  golang-ci-lint-args:
    description: Additional arguments for golangci-lint
    type: string
    required: false
    default: '--timeout=10m'
  skip-lint:
    description: Check whether to skip lint step
    type: boolean
    required: false
    default: false
  skip-build:
    description: Check whether to skip build step
    type: boolean
    required: false
    default: false
  skip-test:
    description: Check whether to skip test step
    type: boolean
    required: false
    default: false
  artifact-name:
    description: The name of the artifact to upload
    type: string
    required: false
    default: 'dist'
  output-dir:
    description: The path to the output directory
    type: string
    required: false
    default: 'dist/'

runs:
  using: "composite"
  steps:
    - name: Set working directory
      env:
        WORKING_DIR: "${{ inputs.project-path }}"
      shell: bash
      run: echo "WORKING_DIR=${WORKING_DIR:-.}" >> "$GITHUB_ENV"

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}
        cache-dependency-path: ${{ env.WORKING_DIR }}/go.sum

    - name: Run golangci-lint
      if: inputs.skip-lint == 'false'
      uses: golangci/golangci-lint-action@v3
      with:
        version: ${{ inputs.golang-ci-lint-version }}
        args: ${{ inputs.golang-ci-lint-args }}
        working-directory: ${{ env.WORKING_DIR }}

    - name: Skip running golangci-lint
      if: inputs.skip-lint == 'true'
      shell: bash
      run: echo "Skipped running golangci-lint"

    - name: Build
      if: inputs.skip-build == 'false'
      env:
        OUTPUT_DIR: ${{ inputs.output-dir }}
      shell: bash
      working-directory: ${{ env.WORKING_DIR }}
      run: go build -o ${OUTPUT_DIR} -v ./...

    - name: Upload artifact
      if: inputs.skip-build == 'false' && success()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: "${{ env.WORKING_DIR }}/${{ inputs.output-dir }}"

    - name: Skip building
      if: inputs.skip-build == 'true'
      shell: bash
      run: echo "Skipped building"

    - name: Test
      if: inputs.skip-test == 'false'
      shell: bash
      working-directory: ${{ env.WORKING_DIR }}
      run: go test -v ./...

    - name: Skip testing
      if: inputs.skip-test == 'true'
      shell: bash
      run: echo "Skipped testing"

branding:
  icon: 'box'
  color: 'green'
