name: Test

on:
  push:
    tags:
      - v*
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        go-version:
          - '1.18'
          - '1.19'
          - '1.20'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test action without skipping any step
        uses: ./
        with:
          project-path: tests/dummy_app
          go-version: ${{ matrix.go-version }}
          artifact-name: "dummy-app-${{ matrix.os }}-go-${{ matrix.go-version }}"

      - name: Test action with skipping lint
        uses: ./
        with:
          project-path: tests/dummy_app
          go-version: ${{ matrix.go-version }}
          skip-lint: true

      - name: Test action with skipping build
        uses: ./
        with:
          project-path: tests/dummy_module
          go-version: ${{ matrix.go-version }}
          skip-build: true

      - name: Test action with skipping test
        uses: ./
        with:
          project-path: tests/dummy_app
          go-version: ${{ matrix.go-version }}
          skip-test: true
